// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNqdqaJuBZnQVMt2ZWUB80RNZN_1v8jk',
    appId: '1:978296909807:android:55cf0fd2b5fc5f7bdf501a',
    messagingSenderId: '978296909807',
    projectId: 'news-app-66aa3',
    databaseURL: 'https://news-app-66aa3-default-rtdb.firebaseio.com',
    storageBucket: 'news-app-66aa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuY27J-iUxqAf0R8R9FnxNS_Ei-TSbxHY',
    appId: '1:978296909807:ios:75c49eb7e415d036df501a',
    messagingSenderId: '978296909807',
    projectId: 'news-app-66aa3',
    databaseURL: 'https://news-app-66aa3-default-rtdb.firebaseio.com',
    storageBucket: 'news-app-66aa3.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );
}
